#!/usr/bin/env python3
"""
Highlight spoken Spanish diphthong *letters* in spanish-cheatsheet.md.

Wraps only the diphthong cluster, e.g.:
  baile  →  b<span class="diphthong">ai</span>le
  bueno  →  b<span class="diphthong">ue</span>no
  día    →  día   (hiatus — not marked)
  guerra →  guerra  (silent u in gue — not marked)

Safe to re-run. Usage (from project root or scripts/):
  python scripts/mark_diphthongs.py
"""

from __future__ import annotations

import re
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent
ROOT = SCRIPTS.parent
TARGET = ROOT / "spanish-cheatsheet.html"

# Longest first so güe/güi beat ue/ui
DIPHTHONG_FIND_RE = re.compile(
    r"(?i)("
    r"güe|güi|"
    r"ái|áu|éi|éu|ói|óu|"
    r"iá|ié|ió|iú|"
    r"uá|ué|uí|uó|"
    r"ai|au|ei|eu|oi|ou|"
    r"ia|ie|io|iu|"
    r"ua|ue|ui|uo|"
    r"ay|ey|oy|uy"
    r")"
)

HIATUS_RE = re.compile(r"(?i)(ía|íe|ío|íu|úa|úe|úi|úo|aí|eí|oí|aú|eú|oú)")

# Silent-u sequences that look like ue/ui but are NOT diphthongs
SILENT_U_RE = re.compile(r"(?i)(?:q|g)u(?=[eéií])")

WORD_RE = re.compile(r"[A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+(?:'[A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+)?")

SPANISH_HINT = re.compile(r"[áéíóúüñÁÉÍÓÚÜÑ¿¡]")

ENGLISH_SKIP = {
    "the",
    "and",
    "for",
    "with",
    "from",
    "this",
    "that",
    "these",
    "those",
    "when",
    "what",
    "where",
    "which",
    "while",
    "who",
    "whom",
    "whose",
    "why",
    "how",
    "pronunciation",
    "special",
    "especially",
    "information",
    "section",
    "sections",
    "question",
    "questions",
    "example",
    "examples",
    "default",
    "difference",
    "differences",
    "different",
    "foundation",
    "combination",
    "combinations",
    "conversation",
    "conversations",
    "description",
    "descriptions",
    "condition",
    "conditions",
    "action",
    "actions",
    "location",
    "locations",
    "emotion",
    "emotions",
    "opinion",
    "opinions",
    "duration",
    "relation",
    "relationship",
    "optional",
    "previous",
    "media",
    "usual",
    "usually",
    "actual",
    "actually",
    "visual",
    "material",
    "serial",
    "period",
    "various",
    "audio",
    "video",
    "europe",
    "european",
    "guide",
    "guides",
    "idea",
    "ideas",
    "area",
    "areas",
    "create",
    "created",
    "creating",
    "because",
    "before",
    "between",
    "below",
    "above",
    "about",
    "after",
    "again",
    "being",
    "their",
    "there",
    "other",
    "another",
    "either",
    "neither",
    "whether",
    "rather",
    "further",
    "under",
    "over",
    "into",
    "onto",
    "also",
    "only",
    "just",
    "like",
    "than",
    "then",
    "them",
    "they",
    "thus",
    "both",
    "some",
    "same",
    "such",
    "more",
    "most",
    "much",
    "many",
    "very",
    "well",
    "good",
    "best",
    "better",
    "less",
    "least",
    "first",
    "last",
    "next",
    "each",
    "every",
    "any",
    "all",
    "few",
    "own",
    "out",
    "off",
    "down",
    "up",
    "here",
    "now",
    "still",
    "already",
    "always",
    "never",
    "often",
    "sometimes",
    "please",
    "thanks",
    "thank",
    "hello",
    "goodbye",
    "yes",
    "no",
    "not",
    "nor",
    "but",
    "or",
    "if",
    "so",
    "as",
    "at",
    "by",
    "on",
    "in",
    "of",
    "to",
    "too",
    "two",
    "one",
    "once",
    "use",
    "used",
    "using",
    "user",
    "you",
    "your",
    "yours",
    "we",
    "our",
    "ours",
    "he",
    "she",
    "it",
    "its",
    "his",
    "her",
    "hers",
    "him",
    "me",
    "my",
    "mine",
    "i",
    "am",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "could",
    "should",
    "may",
    "might",
    "must",
    "can",
    "need",
    "see",
    "look",
    "read",
    "write",
    "say",
    "said",
    "tell",
    "told",
    "get",
    "got",
    "go",
    "goes",
    "going",
    "come",
    "came",
    "make",
    "made",
    "take",
    "took",
    "give",
    "gave",
    "find",
    "found",
    "know",
    "knew",
    "think",
    "thought",
    "want",
    "try",
    "tried",
    "leave",
    "left",
    "keep",
    "kept",
    "let",
    "begin",
    "seem",
    "help",
    "show",
    "hear",
    "play",
    "run",
    "move",
    "live",
    "believe",
    "hold",
    "bring",
    "happen",
    "provide",
    "sit",
    "stand",
    "lose",
    "pay",
    "meet",
    "include",
    "continue",
    "set",
    "learn",
    "change",
    "lead",
    "understand",
    "watch",
    "follow",
    "stop",
    "speak",
    "allow",
    "add",
    "spend",
    "grow",
    "open",
    "walk",
    "win",
    "offer",
    "remember",
    "love",
    "consider",
    "appear",
    "buy",
    "wait",
    "serve",
    "die",
    "send",
    "expect",
    "build",
    "stay",
    "fall",
    "cut",
    "reach",
    "kill",
    "remain",
    "suggest",
    "raise",
    "pass",
    "sell",
    "require",
    "report",
    "decide",
    "pull",
    "spain",
    "spanish",
    "english",
    "latin",
    "america",
    "american",
    "mexico",
    "castilian",
    "preview",
    "editor",
    "window",
    "reload",
    "developer",
    "markdown",
    "details",
    "summary",
    "document",
    "file",
    "folder",
    "style",
    "styles",
    "spacing",
    "layout",
    "format",
    "formatting",
    "table",
    "tables",
    "column",
    "row",
    "click",
    "press",
    "hold",
    "collapse",
    "expand",
    "triangle",
    "triangles",
    "chevron",
    "chevrons",
    "gutter",
    "outline",
    "workspace",
    "setting",
    "settings",
    "value",
    "values",
    "currently",
    "content",
    "title",
    "note",
    "notes",
    "tip",
    "tips",
    "rule",
    "rules",
    "pattern",
    "patterns",
    "sound",
    "sounds",
    "letter",
    "letters",
    "combo",
    "combos",
    "word",
    "words",
    "phrase",
    "phrases",
    "sentence",
    "sentences",
    "meaning",
    "meanings",
    "places",
    "differs",
    "covered",
    "church",
    "million",
    "canyon",
    "butter",
    "thin",
    "loch",
    "bach",
    "get",
    "geek",
    "gwen",
    "yes",
    "gem",
    "giant",
    "jam",
    "rose",
    "dog",
    "war",
    "guitar",
    "penguin",
    "shame",
    "embarrassment",
    "zero",
    "dinner",
    "movie",
    "theater",
    "people",
    "sunflower",
    "ham",
    "game",
    "friend",
    "house",
    "table",
    "milk",
    "island",
    "book",
    "sun",
    "moon",
    "blue",
    "elephant",
    "water",
    "city",
    "rain",
    "street",
    "cheese",
    "wanted",
    "guide",
    "exam",
    "shoe",
    "bread",
    "gold",
    "child",
    "boy",
    "night",
    "mom",
    "dad",
    "cat",
    "hour",
    "egg",
    "family",
    "day",
    "cow",
    "wine",
    "drink",
    "fine",
    "baby",
    "grape",
    "today",
    "noun",
    "casual",
    "without",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    "january",
    "february",
    "restaurant",
    "weather",
    "children",
    "morning",
    "afternoon",
    "evening",
    "welcome",
    "excuse",
    "sorry",
    "maybe",
    "several",
    "certain",
    "really",
    "probably",
    "perhaps",
    "quite",
    "almost",
    "instead",
    "indeed",
    "otherwise",
    "however",
    "therefore",
    "meanwhile",
    "besides",
    "although",
    "though",
    "unless",
    "until",
    "whereas",
    "shall",
    "having",
    "doing",
    "been",
    "being",
    "highlight",
    "highlighted",
    "underline",
    "yellow",
    "diphthong",
    "diphthongs",
    "hiatus",
    "spoken",
    "cluster",
    "clusters",
    "gliding",
    "syllable",
    "syllables",
    "strong",
    "weak",
    "silent",
    "reload",
    "eye",
    "beyn",
    "sayss",
    "dyohs",
    "byeh",
    "byehn",
    "kyehn",
    "kwahn",
    "syahs",
    "thyahs",
    "syoo",
    "thyoo",
    "nyoh",
    "nyah",
    "gwah",
    "weh",
}

SPANISH_DIPHTHONG_WORDS = {
    "muy",
    "hay",
    "soy",
    "voy",
    "doy",
    "hoy",
    "rey",
    "ley",
    "buey",
    "bien",
    "quien",
    "cual",
    "cuando",
    "cuanto",
    "donde",
    "como",
    "hacia",
    "luego",
    "mientras",
    "siempre",
    "tambien",
    "tampoco",
    "aunque",
    "porque",
    "bueno",
    "buena",
    "buenos",
    "buenas",
    "nueve",
    "nuevo",
    "nueva",
    "nuevos",
    "nuevas",
    "puede",
    "puedo",
    "puedes",
    "pueden",
    "podemos",
    "quiero",
    "quieres",
    "quiere",
    "quieren",
    "tiene",
    "tienen",
    "tienes",
    "tengo",
    "viene",
    "vienes",
    "vienen",
    "vengo",
    "ciudad",
    "ciudades",
    "familia",
    "familias",
    "gracias",
    "adios",
    "europa",
    "europea",
    "europeo",
    "cuota",
    "ruido",
    "viuda",
    "cuidado",
    "cuidados",
    "piano",
    "aire",
    "baile",
    "bailes",
    "causa",
    "causas",
    "auto",
    "autos",
    "reina",
    "oigo",
    "tierra",
    "cielo",
    "piedra",
    "fiesta",
    "fiestas",
    "tiempo",
    "tiempos",
    "despues",
    "estacion",
    "estaciones",
    "accion",
    "leccion",
    "cancion",
    "nacion",
    "opcion",
    "habitacion",
    "informacion",
    "conversacion",
    "nuestro",
    "nuestra",
    "nuestros",
    "nuestras",
    "vuestro",
    "vuestra",
    "vuestros",
    "vuestras",
    "mio",
    "mia",
    "mios",
    "mias",
    "tuyo",
    "tuya",
    "tuyos",
    "tuyas",
    "suyo",
    "suya",
    "suyos",
    "suyas",
    "nosotros",
    "nosotras",
    "vosotros",
    "vosotras",
    "ellos",
    "ellas",
    "usted",
    "ustedes",
    "cualquier",
    "cuales",
    "quienes",
    "cuantos",
    "cuantas",
    "puerta",
    "puertas",
    "siete",
    "diez",
    "seis",
    "veinte",
    "treinta",
    "cuarenta",
    "cincuenta",
    "sesenta",
    "setenta",
    "ochenta",
    "noventa",
    "ciento",
    "doscientos",
    "trescientos",
    "cuatrocientos",
    "quinientos",
    "seiscientos",
    "setecientos",
    "ochocientos",
    "novecientos",
    "millon",
    "millones",
    "primero",
    "primera",
    "segundo",
    "segunda",
    "tercero",
    "tercera",
    "cuarto",
    "cuarta",
    "quinto",
    "quinta",
    "sexto",
    "sexta",
    "septimo",
    "septima",
    "octavo",
    "octava",
    "noveno",
    "novena",
    "decimo",
    "decima",
    "junio",
    "julio",
    "diciembre",
    "estudio",
    "estudias",
    "estudia",
    "estudiamos",
    "estudian",
    "estudiar",
    "estudiante",
    "estudiantes",
    "agua",
    "fue",
    "fui",
    "fuimos",
    "fueron",
    "cuesta",
    "cuestan",
    "juego",
    "juega",
    "juegas",
    "juegan",
    "juegos",
    "abuelo",
    "abuela",
    "abuelos",
    "abuelas",
    "nieto",
    "nieta",
    "nietos",
    "nietas",
    "suegro",
    "suegra",
    "cunado",
    "cunada",
    "novio",
    "novia",
    "niebla",
    "nieva",
    "llueve",
    "lluvia",
    "llave",
    "llaves",
    "llega",
    "llego",
    "llegas",
    "llegan",
    "llegar",
    "llamar",
    "llamo",
    "llamas",
    "llaman",
    "igual",
    "igualmente",
    "despacio",
    "espacio",
    "especie",
    "antigua",
    "antiguo",
    "ciencia",
    "consigo",
    "contigo",
    "conmigo",
    "italia",
    "italiano",
    "italiana",
    "medio",
    "media",
    "medios",
    "medias",
    "pie",
    "pies",
    "prueba",
    "pruebas",
    "pueblo",
    "pueblos",
    "puente",
    "puerto",
    "quieto",
    "radio",
    "radios",
    "realidad",
    "realmente",
    "recuerdo",
    "recuerdos",
    "restaurante",
    "restaurantes",
    "reunion",
    "salida",
    "salidas",
    "sangre",
    "siento",
    "sientes",
    "siendo",
    "sitio",
    "sitios",
    "socio",
    "suave",
    "suaves",
    "sube",
    "subir",
    "suelo",
    "suena",
    "sueno",
    "tienda",
    "tiendas",
    "todavia",
    "trabajo",
    "trabajos",
    "trae",
    "traer",
    "traje",
    "trajes",
    "trueque",
    "tuve",
    "tuvimos",
    "tuvieron",
    "ultimo",
    "ultima",
    "universidad",
    "universidades",
    "vacaciones",
    "varios",
    "varias",
    "veintiuno",
    "ventana",
    "ventanas",
    "verano",
    "verdad",
    "verdadero",
    "viaje",
    "viajes",
    "viajar",
    "viajo",
    "viejo",
    "vieja",
    "viejos",
    "viejas",
    "viento",
    "viernes",
    "viviendo",
    "volviendo",
    "vuelve",
    "vuelvo",
    "vuelves",
    "vuelven",
    "vuelta",
    "vueltas",
    "yegua",
    "yeso",
    "yoga",
    "cuanto",
    "cuando",
    "donde",
    "como",
    "quien",
    "cual",
    "guia",
    "pinguino",
    "verguenza",
    "cien",
    "dieciseis",
    "diecisiete",
    "dieciocho",
    "diecinueve",
    "veintidos",
    "veintitres",
    "veintiseis",
    "despues",
    "tambien",
    "asi",
    "aqui",
    "alli",
    "alla",
    "adonde",
    "ningun",
    "ninguna",
    "ninguno",
    "ningunos",
    "ningunas",
    "alguien",
    "nadie",
    "cualquiera",
    "demasiado",
    "demasiada",
    "demasiados",
    "demasiadas",
    "recien",
    "baile",
    "bueno",
    "tiene",
    "ciudad",
    "muy",
    "hay",
    "soy",
}


def is_pronunciation_guide(word: str) -> bool:
    if "-" in word:
        return True
    letters = re.sub(r"[^A-Za-zÁÉÍÓÚÜÑáéíóúüñ]", "", word)
    if letters and letters == letters.upper() and len(letters) <= 12:
        if not SPANISH_HINT.search(word) and re.fullmatch(r"[A-Z]+", letters):
            return True
    return False


def word_is_spanish_context(word: str) -> bool:
    low = word.lower()
    if low in ENGLISH_SKIP:
        return False
    if is_pronunciation_guide(word):
        return False
    if SPANISH_HINT.search(word):
        return True
    if low in SPANISH_DIPHTHONG_WORDS:
        return True
    if re.search(
        r"(?i)(ción|sión|dad|tad|mente|idad|ando|iendo|arse|erse|irse|"
        r"amos|emos|imos|áis|éis|aba|aban|aste|aron|ido|ada|ados|adas)$",
        word,
    ):
        return True
    return False


def blocked_ranges(word: str) -> list[tuple[int, int]]:
    """Index ranges that must not be marked as diphthongs."""
    blocked: list[tuple[int, int]] = []
    # Hiatus clusters
    for m in HIATUS_RE.finditer(word):
        blocked.append((m.start(), m.end()))
    # Silent u in que/qui/gue/gui: block the "u" + following weak/strong vowel pair
    # e.g. guerra: positions of "ue"; queso: "ue"; guitarra: "ui"
    for m in SILENT_U_RE.finditer(word):
        # m is q/g + u looking ahead at e/i; block from u through that vowel
        u_index = m.end() - 1  # the 'u'
        # vowel is next char
        if u_index + 1 < len(word):
            blocked.append((u_index, u_index + 2))
    return blocked


def overlaps(a: tuple[int, int], b: tuple[int, int]) -> bool:
    return not (a[1] <= b[0] or b[1] <= a[0])


def find_diphthong_spans(word: str) -> list[tuple[int, int]]:
    """Return non-overlapping (start, end) spans of spoken diphthongs in word."""
    if not word_is_spanish_context(word):
        return []

    blocked = blocked_ranges(word)
    candidates: list[tuple[int, int]] = []
    for m in DIPHTHONG_FIND_RE.finditer(word):
        span = (m.start(), m.end())
        if any(overlaps(span, b) for b in blocked):
            continue
        candidates.append(span)

    # Greedy non-overlapping left-to-right (patterns already longest-first in alternation)
    candidates.sort(key=lambda s: (s[0], -(s[1] - s[0])))
    chosen: list[tuple[int, int]] = []
    for span in candidates:
        if any(overlaps(span, c) for c in chosen):
            continue
        chosen.append(span)
    chosen.sort(key=lambda s: s[0])
    return chosen


def wrap_spans_in_word(word: str) -> str:
    spans = find_diphthong_spans(word)
    if not spans:
        return word
    parts: list[str] = []
    i = 0
    for start, end in spans:
        parts.append(word[i:start])
        parts.append(f'<span class="diphthong">{word[start:end]}</span>')
        i = end
    parts.append(word[i:])
    return "".join(parts)


def unwrap_existing(text: str) -> str:
    # Remove diphthong spans (possibly nested leftover full-word marks)
    prev = None
    while prev != text:
        prev = text
        text = re.sub(
            r'<span class="diphthong">([^<]*)</span>',
            r"\1",
            text,
        )
    return text


def process_text(text: str) -> tuple[str, int]:
    count = 0
    parts = re.split(r"(<[^>]+>)", text)
    out: list[str] = []
    in_diphthong_span = 0

    for part in parts:
        if part.startswith("<"):
            if re.match(r'(?i)<span\b[^>]*class=["\'][^"\']*\bdiphthong\b', part):
                in_diphthong_span += 1
            elif re.match(r"(?i)</span\s*>", part) and in_diphthong_span:
                in_diphthong_span = max(0, in_diphthong_span - 1)
            out.append(part)
            continue
        if in_diphthong_span:
            out.append(part)
            continue

        def repl(m: re.Match) -> str:
            nonlocal count
            w = m.group(0)
            spans = find_diphthong_spans(w)
            if not spans:
                return w
            count += len(spans)
            return wrap_spans_in_word(w)

        out.append(WORD_RE.sub(repl, part))

    return "".join(out), count


def main() -> None:
    raw = TARGET.read_text(encoding="utf-8")
    cleaned = unwrap_existing(raw)
    updated, n = process_text(cleaned)
    TARGET.write_text(updated, encoding="utf-8")
    print(f"Marked {n} diphthong letter-clusters in {TARGET.name}")


if __name__ == "__main__":
    main()
